version: "3.3"

services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "9090:9090"
    environment:
      NIFI_WEB_HTTP_PORT: '9090'
    volumes:
        - "<path_to_jdbc>/:/jdbc"

  nifi_registry:
    image: apache/nifi-registry:latest
    ports:
      - "19090:19090"
    environment:
      NIFI_REGISTRY_WEB_HTTP_PORT: '19090'
