version: '3'
services:
  registry:
    image: registry:latest
    restart: always
    ports:
    - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /path/data:/var/lib/registry /* раздел который будет использоваться как хранилище для вашего репозитория*/
      - /path/certs:/certs /* папка где хранитcя сертификат */
      - /path/auth:/auth
